AWSTemplateFormatVersion: '2010-09-09'
Description: AthenaQueryPollModeActivity
Outputs:
  AthenaQueryExecution:
    Value:
      Ref: AthenaQueryExecution
Resources:
  AthenaQueryExecution:
    Properties:
      DefinitionString:
        Fn::Sub: "{\n  \"Comment\": \"Poll task pattern\",\n  \"StartAt\": \"start_query\"\
          ,\n  \"States\": {\n    \"start_query\": {\n      \"Type\": \"Task\",\n\
          \      \"Resource\": \"${AthenaRunnerStartQuery.Arn}\",\n      \"Next\"\
          : \"wait_next\"\n    },\n    \"wait_next\": {\n      \"Type\": \"Wait\"\
          ,\n      \"SecondsPath\": \"$.waitTime\",\n      \"Next\": \"poll_status\"\
          \n    },\n    \"poll_status\": {\n      \"Type\": \"Task\",\n      \"Resource\"\
          : \"${AthenaRunnerPollStatus.Arn}\",\n      \"Next\": \"check_complete\"\
          \n    },\n    \"check_complete\": {\n      \"Type\": \"Choice\",\n     \
          \ \"Default\": \"wait_next\",\n      \"Choices\": [\n        {\n       \
          \   \"Variable\": \"$.status\",\n          \"StringEquals\": \"FAILED\"\
          ,\n          \"Next\": \"query_failed\"\n        },\n        {\n       \
          \   \"Variable\": \"$.status\",\n          \"StringEquals\": \"SUCCEEDED\"\
          ,\n          \"Next\": \"get_results\"\n        }\n      ]\n    },\n   \
          \ \"query_failed\": {\n      \"Type\": \"Fail\",\n      \"Cause\": \"Athena\
          \ execution failed\",\n      \"Error\": \"Athena execution failed\"\n  \
          \  },\n    \"get_results\": {\n      \"Type\": \"Task\",\n      \"Resource\"\
          : \"${AthenaRunnerGetResults.Arn}\",\n      \"End\": true\n    }\n  }\n\
          }\n"
      RoleArn:
        Fn::GetAtt:
        - AthenaQueryExecutionStepFn
        - Arn
    Type: AWS::StepFunctions::StateMachine
  AthenaQueryExecutionStepFn:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
              Fn::Sub: states.${AWS::Region}.amazonaws.com
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - lambda:*
            - iam:*
            Effect: Allow
            Resource: '*'
        PolicyName: lambda
    Type: AWS::IAM::Role
  AthenaRunnerGetResults:
    Properties:
      CodeUri: s3://ards-lambda-repo/240e33058ee8ba85882d90f6e9a941d0
      Handler: athena.getResults
      Role:
        Fn::GetAtt:
        - LambdaAthenaQueryExecutionRole
        - Arn
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  AthenaRunnerPollStatus:
    Properties:
      CodeUri: s3://ards-lambda-repo/240e33058ee8ba85882d90f6e9a941d0
      Handler: athena.pollStatus
      Role:
        Fn::GetAtt:
        - LambdaAthenaQueryExecutionRole
        - Arn
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  AthenaRunnerStartQuery:
    Properties:
      CodeUri: s3://ards-lambda-repo/240e33058ee8ba85882d90f6e9a941d0
      Handler: athena.startQuery
      Role:
        Fn::GetAtt:
        - LambdaAthenaQueryExecutionRole
        - Arn
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  LambdaAthenaQueryExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - cloudwatch:*
            - s3:*
            - lambda:*
            - iam:*
            - cloudformation:*
            - ec2:*
            - sdb:*
            - support:*
            - athena:*
            - glue:*
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: LambdaAthenaQueryExecutionPolicy
    Type: AWS::IAM::Role
  StepExecManageRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /service-role/
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - states:*
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: AthenaQueryStepFunction
    Type: AWS::IAM::Role
  TLOGSync:
    DependsOn:
    - StepExecManageRole
    - AthenaQueryExecution
    Properties:
      Description: ScheduledRule
      ScheduleExpression: rate(1 minute)
      State: ENABLED
      Targets:
      - Arn:
          Ref: AthenaQueryExecution
        Id: FOO123
        Input:
          Fn::Sub: "{\n  \"query\": \"SELECT * FROM \\\"sampledb\\\".\\\"elb_logs\\\
            \" limit 10;\",\n  \"outputLocation\": \"s3://ards-us-west-athena-results\"\
            \n}\n"
        RoleArn:
          Fn::GetAtt:
          - StepExecManageRole
          - Arn
    Type: AWS::Events::Rule
Transform:
- AWS::Serverless-2016-10-31
