---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'ScheduledRule'
Transform:
- 'AWS::Serverless-2016-10-31'
Resources:
  TLOGSync:
    Type: "AWS::Events::Rule"
    Properties:
      Description: "ScheduledRule"
      ScheduleExpression: "rate(10 minutes)"
      State: "ENABLED"
      Targets:
      - Arn: arn:aws:states:us-west-2:586705174353:stateMachine:AthenaQueryExecution-lSkOYjdfXRcv
        Id: ABC1233
        RoleArn: !GetAtt EventManageRole.Arn
        Input: !Sub |
          {
            "query": "SELECT * FROM \"sampledb\".\"elb_logs\" limit 10;",
            "outputLocation": "s3://ards-us-west-athena-results"
          }
  EventManageRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/service-role/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service: "lambda.amazonaws.com"
          Action: "sts:AssumeRole"
      Policies:
      - PolicyName: "LambdaEMRSetup"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Resource: arn:aws:states:us-west-2:586705174353:stateMachine:AthenaQueryExecution-lSkOYjdfXRcv
              Action:
              - "states:StartExecution"
